version: "3.7"

services:
  node:
    image: "node:12"
    user: "node"
    working_dir: /home/node/app
    container_name: testnodeapp
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "8081"
    command: "npm start"
                        
