version: "3.9"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  nodeserver:
    image: "node:12"
    user: "node"
    ports:
      - "3000:3000"
    working_dir: /home/node/app
    environment:
      - NODE_ENV:development
    volumes:
      - ./nodeserver:/home/node/app
    command: "npm start"
                        
  frontend:
    image: "node:12"
    user: "node"
    working_dir: /home/node/frontend
    volumes:
      - ./frontend:/home/node/frontend
    ports:
      - "8080:8080"
    command: "npm run serve"
